spring:
  application:
    name: backend-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:spring-security
    username: root
    password: 12345


springdoc:
  default-produces-media-type: "application/json"
  default-consumes-media-type: "application/json" #default value


token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
